name: Build and send diploma thesis
description: GitHub action to build and send a diploma thesis using the corresponding Docker image from the school HTL Leoben
author: Marko Schrempf
branding:
  icon: book
  color: orange

inputs:
  target:
    description: The target used to build the diploma thesis. It supports one target per run which is one out of 'pdf', 'spellcheck' or 'tex'. If not set it will default to 'pdf'
    default: pdf
    required: false
  mail:
    description: The sending email address
    required: false
  mail-password:
    description: The password for the sending email address
    required: false
  smtp-server:
    description: The SMTP server of the sending email
    required: false
  smtp-port:
    description: The SMTP server port of the sending email
    required: false
  receiving-mail:
    description: The email address of the receiving mail address (e.g. Microsoft Teams channel) the diploma thesis is sent to
    required: false
  mail-body:
    description: The body to sent with the email. If not set it will default to the commit message
    required: false

  thesis-path:
    description: The path from the repository root to the filled out diploma thesis folder. If not set it will default to 'Diplomarbeit'
    default: Diplomarbeit
    required: false
  output-dir:
    description: The name of the compilation output folder placed inside the thesis-path folder. If not set it will default to 'out'
    default: out
    required: false
  docker-registry:
    description: The Docker registry from which to pull the image. If not set it will default to 'docker.io'
    default: docker.io
    required: false
  docker-namespace:
    description: The Docker username for the image. If not set it will default to 'bytebang'
    default: bytebang
    required: false
  docker-image:
    description: The Docker repository name for the image. If not set it will default to 'htlle-da-builder'
    default: htlle-da-builder
    required: false
  docker-tag:
    description: The Docker tag used for the image. If not set it will default to 'latest' 
    default: latest
    required: false
  manual-mode:
    description: If the repository should not be checked out automatically specify the complete workspace path to the thesis-path. If not set it will default to checking out the latest repository state
    required: false

runs:
  using: composite

  steps:
    - name: Check Target
      shell: bash
      run: |
        TARGET=$(echo "${{ inputs.target }}" | xargs | tr '[:upper:]' '[:lower:]')
        if [[ "$TARGET" != "pdf" && "$TARGET" != "spellcheck" && "$TARGET" != "tex" ]]; then
          echo "::error::Invalid target: $TARGET. Allowed targets are pdf, spellcheck or tex."
          exit 1
        fi

    - name: Checkout Repository
      if: ${{ !inputs.manual-mode }}
      uses: actions/checkout@v7

    - name: Set thesis-path From manual-mode
      if: ${{ inputs.manual-mode }}
      shell: bash
      run: echo "thesis-path=${{ inputs.manual-mode }}/${{ inputs.thesis-path }}" >> $GITHUB_ENV

    - name: Cache Docker Image
      id: cache-docker
      uses: actions/cache@v6
      with:
        path: /tmp/.docker
        key: docker-${{ inputs.docker-namespace }}-${{ inputs.docker-image }}-${{ hashFiles('**/da-base-template/tools/docker/Dockerfile') }}
        restore-keys: docker-${{ inputs.docker-namespace }}-${{ inputs.docker-image }}

    - name: Create Docker Cache Directory
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir -p /tmp/.docker

    - name: Load Cached Docker Image
      if: steps.cache-docker.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i /tmp/.docker/image.tar

    - name: Pull Docker Image
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: docker pull ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }}
        docker save ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }} -o /tmp/.docker/image.tar

    - name: Build Diploma Thesis
      shell: bash
      run: docker run --rm \
          -u $(id -u):$(id -g) \
          -v "${{ github.workspace }}/${{ inputs.thesis-path }}:/workspace:rw" \
          -e TARGETS=${{ inputs.target }} \
          ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }}

    - name: Get UTC Timestamp
      id: timestamp
      shell: bash
      run: echo "datetime=$(date -u +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_OUTPUT

    #- name: Rename PDF With Timestamp
      #if: ${{ inputs.target == 'pdf' }}
      #shell: bash
      #run: mv ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit.pdf ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}.pdf

    #- name: Rename Spellcheck With Timestamp
      #if: ${{ inputs.target == 'spellcheck' }}
      #shell: bash
      #run: mv ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/spellcheck-results.txt ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/spellcheck-results-${{ steps.timestamp.outputs.datetime }}.
      
    #- name: Rename LaTeX With Timestamp
      #if: ${{ inputs.target == 'tex' }}
      #shell: bash
      #run: mv ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit.pdf.tex ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}.pdf.tex

    #- name: Upload Diploma Thesis
      #uses: actions/upload-artifact@v7
      #with:
        #name: diplomarbeit-${{ steps.timestamp.outputs.datetime }}
        #path: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}.pdf

    - name: Upload Diploma Thesis Artifact
      uses: actions/upload-artifact@v7
      with:
        name: diplomarbeit-${{ steps.timestamp.outputs.datetime }}
        path: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}.zip

    - name: Zip Output Directory
      shell: bash
      run: cd ${{ inputs.thesis-path }}/${{ inputs.output-dir }}
        zip -r diplomarbeit-${{ steps.timestamp.outputs.datetime }}.zip .

    - name: Extract Commit Message
      if: ${{ inputs.mail != '' && inputs.mail-password != '' && inputs.smtp-server != '' && inputs.smtp-port != '' && inputs.receiving-mail != '' && inputs.mail-body == '' }}
      id: message
      shell: bash
      run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Send Diploma Thesis
      if: ${{ inputs.mail != '' && inputs.mail-password != '' && inputs.smtp-server != '' && inputs.smtp-port != '' && inputs.receiving-mail != '' }}
      uses: dawidd6/action-send-mail@v18
      with:
        username: ${{ inputs.mail }}
        password: ${{ inputs.mail-password }}
        server_address: ${{ inputs.smtp-server }}
        server_port: ${{ inputs.smtp-port }}
        to: ${{ inputs.receiving-mail }}
        from: ${{ inputs.mail }}
        subject: "Diplomarbeit"
        body: ${{ inputs.mail-body || steps.message.outputs.commit_message }}
        attachments: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}.zip
