name: Build and send diploma thesis
description: GitHub action to build and send a diploma thesis using the corresponding Docker image from the school HTL Leoben
author: Marko Schrempf
branding:
  icon: book
  color: orange

inputs:
  target:
    description: The target used to build the diploma thesis. It supports one target per run which is one out of 'pdf', 'spellcheck' or 'tex'. Defaults to 'pdf'
    default: pdf
    required: false
  send-mail-on-target:
    description: Comma-separated list of targets that trigger an email notification. It supports the same targets as in target and 'all'. Defaults to 'pdf'.
    default: pdf
    required: false
  mail:
    description: The sending email address
    required: false
  mail-password:
    description: The password for the sending email address
    required: false
  smtp-server:
    description: The SMTP server of the sending email
    required: false
  smtp-port:
    description: The SMTP server port of the sending email
    required: false
  receiving-mails:
    description: The email address of the receiving mail address (e.g. Microsoft Teams channel) the diploma thesis is sent to
    required: false
  mail-body:
    description: The body to sent with the email. If not set it will default to the commit message
    required: false

  thesis-path:
    description: The path from the repository root to the filled out diploma thesis folder. Defaults to 'Diplomarbeit'
    default: Diplomarbeit
    required: false
  output-dir:
    description: The name of the compilation output folder placed inside the thesis-path folder. Defaults to 'out'
    default: out
    required: false
  docker-registry:
    description: The Docker registry from which to pull the image. Defaults to 'docker.io'
    default: docker.io
    required: false
  docker-namespace:
    description: The Docker username for the image. Defaults to 'bytebang'
    default: bytebang
    required: false
  docker-image:
    description: The Docker repository name for the image. Defaults to 'htlle-da-builder'
    default: htlle-da-builder
    required: false
  docker-tag:
    description: The Docker tag used for the image. Defaults to 'latest' 
    default: latest
    required: false
  manual-mode:
    description: If the repository should not be checked out automatically specify the complete workspace path to the thesis-path. Defaults to checking out the latest repository state
    required: false

runs:
  using: composite

  steps:
    - name: Check Target
      shell: bash
      run: |
        TARGET=$(echo "${{ inputs.target }}" | xargs | tr '[:upper:]' '[:lower:]')
        if [[ "$TARGET" != "pdf" && "$TARGET" != "spellcheck" && "$TARGET" != "tex" ]]; then
          echo "::error::Invalid target: $TARGET. Allowed targets are pdf, spellcheck or tex."
          exit 1
        fi

    - name: Checkout Repository
      if: ${{ !inputs.manual-mode }}
      uses: actions/checkout@v7

    - name: Set thesis-path From manual-mode
      if: ${{ inputs.manual-mode }}
      shell: bash
      run: echo "thesis-path=${{ inputs.manual-mode }}/${{ inputs.thesis-path }}" >> $GITHUB_ENV

    - name: Cache Docker Image
      id: cache-docker
      uses: actions/cache@v6
      with:
        path: /tmp/.docker
        key: docker-${{ inputs.docker-namespace }}-${{ inputs.docker-image }}-${{ hashFiles('**/da-base-template/tools/docker/Dockerfile') }}
        restore-keys: docker-${{ inputs.docker-namespace }}-${{ inputs.docker-image }}

    - name: Create Docker Cache Directory
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir -p /tmp/.docker

    - name: Load Cached Docker Image
      if: steps.cache-docker.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i /tmp/.docker/image.tar

    - name: Pull Docker Image
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker pull ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }}
        docker save ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }} -o /tmp/.docker/image.tar

    - name: Build Diploma Thesis
      shell: bash
      run: |
        docker run --rm \
          -u $(id -u):$(id -g) \
          -v "${{ github.workspace }}/${{ inputs.thesis-path }}:/workspace:rw" \
          -e TARGETS=${{ inputs.target }} \
          ${{ inputs.docker-registry }}/${{ inputs.docker-namespace }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }}

    - name: Get UTC Timestamp
      id: timestamp
      shell: bash
      run: echo "datetime=$(date -u +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_OUTPUT

    - name: Upload Diploma Thesis Artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/
        name: diplomarbeit-${{ steps.timestamp.outputs.datetime }}-${{ inputs.target }}

    - name: Check Send Mail
      id: check-mail
      shell: bash
      run: |
        ALLOWED_TARGETS=$(echo "${{ inputs.send-mail-on-target }}" | xargs | tr '[:upper:]' '[:lower:]')
        CURRENT_TARGET=$(echo "${{ inputs.target }}" | tr '[:upper:]' '[:lower:]')
        echo "should_send=false" >> $GITHUB_OUTPUT
        
        if [[ "$ALLOWED_TARGETS" == *"all"* ]] || [[ "$ALLOWED_TARGETS" == *"$CURRENT_TARGET"* ]]; then
          echo "should_send=true" >> $GITHUB_OUTPUT
        fi

    - name: Extract Commit Message
      if: ${{ steps.check-mail.outputs.should_send == 'true' && inputs.mail != '' && inputs.mail-password != '' && inputs.smtp-server != '' && inputs.smtp-port != '' && inputs.receiving-mails != '' && inputs.mail-body == '' }}
      id: message
      shell: bash
      run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Send Diploma Thesis
      if: ${{ steps.check-mail.outputs.should_send == 'true' && inputs.mail != '' && inputs.mail-password != '' && inputs.smtp-server != '' && inputs.smtp-port != '' && inputs.receiving-mails != '' }}
      uses: dawidd6/action-send-mail@v18
      with:
        username: ${{ inputs.mail }}
        password: ${{ inputs.mail-password }}
        server_address: ${{ inputs.smtp-server }}
        server_port: ${{ inputs.smtp-port }}
        to: ${{ inputs.receiving-mails }}
        from: ${{ inputs.mail }}
        subject: "Diplomarbeit"
        body: ${{ inputs.mail-body || steps.message.outputs.commit_message }}
        #attachments: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/diplomarbeit-${{ steps.timestamp.outputs.datetime }}-${{ inputs.target }}.zip
        attachments: ${{ inputs.thesis-path }}/${{ inputs.output-dir }}/
