# Author: Marko Schrempf
name: Git Time Calculator

on:
  workflow_dispatch:

jobs:
  calculate-time:
    runs-on: ubuntu-latest

    env:
      TIME_CALCULATOR_PATH: Diplomarbeit/da-base-template/tools/time/time-calculator.py

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get UTC Date
      id: datetime
      run: echo "datetime=$(date -u +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_OUTPUT

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate User Report
      run: python $TIME_CALCULATOR_PATH -u -a -e > user-report-${{ steps.datetime.outputs.datetime }}.json
        
    - name: Generate Issue Report
      run: python $TIME_CALCULATOR_PATH -i -a -e > issue-report-${{ steps.datetime.outputs.datetime }}.json

    - name: Upload User Report
      uses: actions/upload-artifact@v4
      with:
        name: user-report-${{ steps.datetime.outputs.datetime }}
        path: user-report-${{ steps.datetime.outputs.datetime }}.json

    - name: Upload Issue Report
      uses: actions/upload-artifact@v4
      with:
        name: issue-report-${{ steps.datetime.outputs.datetime }}
        path: issue-report-${{ steps.datetime.outputs.datetime }}.json
