name: Build and send diploma thesis

on: 
  #push:
    #branches:
      #- main
    #paths:
      #- Diplomarbeit/**
  workflow_dispatch:

jobs:
  build-send:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [pdf, spellcheck, tex]

    steps:
      - name: Build And Send Diploma Thesis
        uses: bitsneak/DA-Template-Testing@main
        # Uncomment following lines to enable email notification
        with:
          docker-namespace: bitsneak
          docker-image: htlle-da-env
          target: ${{ matrix.target }}
          send-mail-on-target: pdf,spellcheck
          mail: ${{ secrets.SENDING_MAIL }}
          mail-password: ${{ secrets.SENDING_MAIL_PASSWORD }}
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-port: ${{ secrets.SMTP_PORT }}
          receiving-mails: ${{ secrets.RECEIVING_MAILS }}
