name: Git Time Calculator

on:
  push:

jobs:
  calculate-time:
    runs-on: ubuntu-latest

    env:
      TIME_CALCULATOR_PATH: Diplomarbeit/da-base-template/tools/time/time-calculator.py

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate User Report
      id: user_report
      run: |
        FILE=$(python $TIME_CALCULATOR_PATH -u -a -ef=)
        echo "file=$FILE" >> $GITHUB_OUTPUT

    - name: Generate Issue Report
      id: issue_report
      run: |
        FILE=$(python $TIME_CALCULATOR_PATH -i -a -ef=)
        echo "file=$FILE" >> $GITHUB_OUTPUT

    - name: Upload User Report
      uses: actions/upload-artifact@v4
      with:
        name: user-time-report
        path: ${{ steps.user_report.outputs.file }}

    - name: Upload Issue Report
      uses: actions/upload-artifact@v4
      with:
        name: issue-time-report
        path: ${{ steps.issue_report.outputs.file }}
